[firebase]
type = "service_account"
project_id = "funerariaapp-5dc3d"
private_key_id = "94a0fb3ed5dcaa320db955001c5ccfb64cb9d71f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnxLXSBRzYbxm3
K3zhw+nCYR3OcJWhZZQmYZqeRifV6J0muKntQ4fyfO5sp1XLDGFbcdP03TLnIUFD
yo7jd+mYSE9Ed3vDigigTzFq4TSAieAPHoCLacj6GaRWoGi3+l/DG2FiRfY7EqCF
jJSxtxGOiwC7WjxqQTD9YeYmdXRjnytO1VXGZDvq3gqYVGsMzQr9Grn4aG51mlD6
37G/SgxseHXF+Esnmmu8TXufJ+6x13SdVxIi5QaxBjJrO30nZIMYSDgA9BQVPHCC
LZks2LFinX3SElT2jjtLwv3dcJ8mvNDidr9QNId1KE7DMqBBADD9gRVRomsNeKqR
6yocm9MhAgMBAAECggEAAvZlbPfqXJMRYC4a0teKVntsTwLqy4NwLdkDvQmTh8a8
TE4bw4mGvgdxYSUqBRLoiauX569BVjZhtOHTCr6x8MoRbVDqEMYXNYldmqQ8Ft25
GShgJ0GkzOf+ZqpDos2WyZH0U2lZuOHHkhcJoLq0BQweaC0PZm8X47bYVl4cLNiW
3rhN8iO8PHEB07qdK/csf01QQG+1R4H3a7ZFioV31pUYuG0DG2/w5jo8jtqPvN3K
OXW6/H2i6xVZTTW1wbKKG8D2zAGR7O+2avVdHsSVozr3iOe5dVHyTtb/7NT+8fYj
8TOotR8jzKN0FMg6hvjSglhIHz01yeB+72MrIMiheQKBgQD3J2vYQQDM0R2fmXKM
GnMJBA2zPCwn0lgg2eGDwtwWMnFs7ysEtSNw86R0MxMBq93fnYggVHyM8IPk8Lzj
3T8UqwLH83NZRiHhR0I45DIjAAQvMm/pK2OvHI8M9RG7sIKUmcbirMSvc/eslrs/
KQAQl7JGsA5u/u/FSGkuATWq/QKBgQDwEFENiUZ4fVVBDnSO2wU++kzw7k4Gw0Vz
ABzgRkJlU6/oUQgIHtaXG2+chtiiQ/Eep/48s7jv3B1WYlFxCj8pNfdfUKcqE1UQ
qPiddHjWQeX+E4epa1Q5AS1pdOi4clH6uFozIPZcpB55lE5F/Koyrrn5ttaBRWzO
tWILhhib9QKBgAbi4ExcM0uBoBOsUNa6fe4IYOFXkdtiLvZrW68yJLOxoBtq5oXx
DhW9lB1wttzbDwmF+B7+e6HpqaMdWgX3SiSnRyKPE+2u2I7QT3YKVaNIAtXVz+xt
Ow/L+ehgg6f5GQpO5o22Rpyk3IfAg2MVH11W/K6fhSdujvuuMtAHVJl5AoGAJ/pv
pRNxWut0YSspGgk7bGt+mLj24YVvcWFZbbgFop43MzcbYU7RacS155lFRnCOHQ7Y
9f7wE3HSqOoiqfKM5i4IjiT+UbF6fxXEoWQeI4BB7vgNpZcsJXoet+syPlU7dcdx
rgYVQQRL1u9twZX8OgiDDCT4v/pxzlLCiyy/uGkCgYEAySLKZixxGKpfMXsFuxbN
6WfJHf1AvaUB5tZi5oIemRohCdyQRXRmyjZGQhKkWng0GMHmMzpwDe6uOhNjpZEr
+H6az3XFRBkEzAF1zvLRKLuUUwugNNXzn9S6S8IHhueLhg7KOoU2tWyi2w4VGevF
wnYWMAzWLpqrljsxnSNcqd0=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@funerariaapp-5dc3d.iam.gserviceaccount.com"
client_id = "113536295489522205407"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40funerariaapp-5dc3d.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
